name: PhysicalFeatures
version: '${project.version}'
api-version: '1.18'
main: org.s1queence.plugin.PhysicalFeatures
depend:
  - S1queenceLib
  - GSit
commands:
  physicalFeatures:
    usage: /pf <get, reload>
    permission: pf.perms.pf
    aliases:
      - pf
  setPlayerFall:
    usage: /setPlayerFall <player> <seconds>
    permission: pf.perms.spf
    aliases:
      - spf
  getUpPlayer:
    usage: /getUpPlayer <player>
    permission: pf.perms.gup
    aliases:
      - gup
  physicalStats:
    usage: /physicalStats <player>
    permission: pf.perms.ps
    aliases:
      - ps